### ISSUE TITLE
Getting NoMethodError after deployment using generic-k8s method

### ISSUE THREAD

**Issue by ashleymichaelwilliams** [DataDog/ecommerce-workshop#159]
Full disclosure, I haven't used this project in quite some time and my fork of the code became outdated with deprecated ruby dependency packages. While trying to get a more recent snapshot of the code, I deployed the project using the latest code from the `main` branch. The default page loads eventually after a couple of refreshes and the DB is populated with records and schema. However the problem is I get this error message when clicking the Cart button or trying to navigate to the `/admin` url. 

![image](https://user-images.githubusercontent.com/9894630/128469990-94a9fed4-18ef-4369-84b0-9ea5a18c1269.png)

 I have tried using all three ads-service folders source code (broken, fixed, errors) with the same result. Also tried alternate code for the other services (discount and store-frontend) with no success.

Something to note is I'm not running Datadog on my cluster presently, but i would imagine this would be fine. I do see errors reported in the logs. 

```[advertisements] 2021-08-06 06:55:40,520 INFO [bootstrap] [ads.py:42] [dd.service=advertisements-service dd.env=development dd.version=1.0.1 dd.trace_id=1143986986509166125 dd.span_id=6884549032686355217] - Total advertisements available: 3
[advertisements] 2021-08-06 06:55:40,688 ERROR [ddtrace.internal.writer] [writer.py:202] [dd.service=advertisements-service dd.env=development dd.version=1.0.1 dd.trace_id=0 dd.span_id=0] - failed to send traces to Datadog Agent at http://172.18.0.5:8126
[advertisements] Traceback (most recent call last):
[advertisements]   File "/usr/local/lib/python3.9/site-packages/ddtrace/internal/writer.py", line 200, in _send_payload
[advertisements]     response = self._put(payload, headers)
[advertisements]   File "/usr/local/lib/python3.9/site-packages/ddtrace/internal/writer.py", line 165, in _put
[advertisements]     conn.request("PUT", self._endpoint, data, headers)
[advertisements]   File "/usr/local/lib/python3.9/http/client.py", line 1257, in request
[advertisements]     self._send_request(method, url, body, headers, encode_chunked)
[advertisements]   File "/usr/local/lib/python3.9/http/client.py", line 1303, in _send_request
[advertisements]     self.endheaders(body, encode_chunked=encode_chunked)
[advertisements]   File "/usr/local/lib/python3.9/http/client.py", line 1252, in endheaders
[advertisements]     self._send_output(message_body, encode_chunked=encode_chunked)
[advertisements]   File "/usr/local/lib/python3.9/http/client.py", line 1012, in _send_output
[advertisements]     self.send(msg)
[advertisements]   File "/usr/local/lib/python3.9/http/client.py", line 952, in send
[advertisements]     self.connect()
[advertisements]   File "/usr/local/lib/python3.9/http/client.py", line 923, in connect
[advertisements]     self.sock = self._create_connection(
[advertisements]   File "/usr/local/lib/python3.9/socket.py", line 843, in create_connection
[advertisements]     raise err
[advertisements]   File "/usr/local/lib/python3.9/socket.py", line 831, in create_connection
[advertisements]     sock.connect(sa)
[advertisements] ConnectionRefusedError: [Errno 111] Connection refused
[advertisements] 2021-08-06 06:55:43,022 INFO [werkzeug] [_internal.py:113] [dd.service=advertisements-service dd.env=development dd.version=1.0.1 dd.trace_id=0 dd.span_id=0] - 10.244.1.5 - - [06/Aug/2021 06:55:43] "GET /ads HTTP/1.1" 200 -
[advertisements] 2021-08-06 06:55:43,025 INFO [bootstrap] [ads.py:25] [dd.service=advertisements-service dd.env=development dd.version=1.0.1 dd.trace_id=1143986986509166125 dd.span_id=3336431127800903886] - attempting to grab banner at 2.jpg
[advertisements] 2021-08-06 06:55:43,027 INFO [werkzeug] [_internal.py:113] [dd.service=advertisements-service dd.env=development dd.version=1.0.1 dd.trace_id=0 dd.span_id=0] - 10.244.1.5 - - [06/Aug/2021 06:55:43] "GET /banners/2.jpg HTTP/1.1" 200 -
```

Any help would be greatly appreciated. Happy to provide more details if necessary. 

Thanks!
-Ash

**Comment by ashleymichaelwilliams** [comment]
I tried disabling Datadog's capabilities (ie. Tracing, profiling, Log Injection) on the Python containers (ads, discount) using the following vars.

```
          - name: DD_LOGS_INJECTION
            value: "false"
          - name: DD_ANALYTICS_ENABLED
            value: "false"
          - name: DD_PROFILING_ENABLED
            value: "false"
          - name: DD_TRACE_ENABLED
            value: "false"
```

Seemed to clear up the Connection refused errors I was getting rhe logs. 


Found the related event in the container log output, which should give some detail around environment config as well as URI path. 🤷🏼 

 {"host":"frontend-698c9d7c79-87nss","application":"store-frontend","environment":"development","time":"2021-08-06T07:43:47.172+00:00","level":"ERROR","level_index":2,"pid":7,"thread":"puma 001","duration_ms":100.9218580002198,"duration":"100.9ms","named_tags":{"request_id":"f88f6271-2225-4125-982d-f17d41ac54b0","dd":{"trace_id":"4206246142976581233","span_id":"309354225905811365","env":"development","service":"store-frontend","version":"1.0.1"}},"name":"Spree::OrdersController","message":"Completed #edit","controller":"Spree::OrdersController","action":"edit","format":"HTML","method":"GET","path":"/cart","view_runtime":0.0,"db_runtime":1.47,"exception_object":"undefined method `[]' for nil:NilClass","status":500,"status_message":"Internal Server Error"}
