### ISSUE TITLE
Unable to deploy Store Fronted Application

### ISSUE THREAD

**Issue by jainrounak6** [DataDog/ecommerce-workshop#315]
Attempting to deploy the stack locally using Docker Compose with the help of a Make command.
`make local-start`
Getting below errors: 

```
2023-10-29 17:33:50 /usr/local/bundle/gems/puma-3.12.6/lib/puma/dsl.rb:43:in `read': No such file or directory @ rb_sysopen - config/puma.rb (Errno::ENOENT)
2023-10-29 17:33:50     from /usr/local/bundle/gems/puma-3.12.6/lib/puma/dsl.rb:43:in `_load_from'
2023-10-29 17:33:50     from /usr/local/bundle/gems/puma-3.12.6/lib/puma/configuration.rb:194:in `block in load'
2023-10-29 17:33:50     from /usr/local/bundle/gems/puma-3.12.6/lib/puma/configuration.rb:194:in `each'
2023-10-29 17:33:50     from /usr/local/bundle/gems/puma-3.12.6/lib/puma/configuration.rb:194:in `load'
2023-10-29 17:33:50     from /usr/local/bundle/gems/puma-3.12.6/lib/puma/launcher.rb:61:in `initialize'
2023-10-29 17:33:50     from /usr/local/bundle/gems/puma-3.12.6/lib/puma/cli.rb:71:in `new'
2023-10-29 17:33:50     from /usr/local/bundle/gems/puma-3.12.6/lib/puma/cli.rb:71:in `initialize'
2023-10-29 17:33:50     from /usr/local/bundle/gems/puma-3.12.6/bin/puma:8:in `new'
2023-10-29 17:33:50     from /usr/local/bundle/gems/puma-3.12.6/bin/puma:8:in `<top (required)>'
2023-10-29 17:33:50     from /usr/local/bundle/bin/puma:23:in `load'
2023-10-29 17:33:50     from /usr/local/bundle/bin/puma:23:in `<main>
```
![Screenshot 2023-10-29 at 17 33 32](https://github.com/DataDog/ecommerce-workshop/assets/35358530/e159f5fa-5d65-4b8a-b9b7-cfb6c4000872)
![Screenshot 2023-10-29 at 17 34 00](https://github.com/DataDog/ecommerce-workshop/assets/35358530/e2bd04f1-7e08-423a-bfcc-46623574f9bf)

**Comment by Vishnupriya9943** [comment]
Make sure to replace "/store-frontend-instrumented-fixed/store-frontend-initial-state" inside docker-compose-latest.yml  because config/puma.rb inside store-frontend-initial-state

```
    volumes:
      - "../../store-frontend/src/store-frontend-instrumented-fixed/store-frontend-initial-state:/app"

```
